package com.codename1.mycompany;

import com.codename1.components.SpanLabel;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Container;
import com.codename1.ui.Toolbar;
import com.codename1.gui.GoogleMap;
import com.codename1.gui.SplashForm;
import com.codename1.gui.EventsForm;
import com.codename1.gui.Myevents;
import com.codename1.gui.WalkthruForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    private Container C1, C2;
    private Form page1;
    private Form page2;

    SpanLabel lb, lb1, lb2;

    public void init(Object context) {
     theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        UIManager.getInstance().setBundle(theme.getL10N("l1", "en"));
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

                 new SplashForm(theme).show();
//          new TestForm(theme).show();
//new Myevents(theme).show();
        
    

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
